FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./

COPY backend/package.json ./backend/
COPY websocket/package.json ./websocket/
COPY worker/package.json ./worker/
COPY pg-db/package.json ./pg-db/
COPY redis-db/package.json ./redis-db/

RUN bun install

COPY websocket ./websocket
COPY pg-db ./pg-db
COPY redis-db ./redis-db

RUN bunx prisma generate --schema=pg-db/prisma/schema.prisma

WORKDIR /app/websocket

EXPOSE 5050

CMD ["bun", "run", "start"]