FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lock ./
#will change it later
COPY backend/package.json ./backend/
COPY frontend/package.json ./frontend/
COPY websocket/package.json ./websocket/
COPY worker/package.json ./worker/
COPY pg-db/package.json ./pg-db/
COPY redis-db/package.json ./redis-db/

RUN bun install --frozen-lockfile

COPY backend ./backend
COPY pg-db ./pg-db
COPY redis-db ./redis-db

RUN bunx prisma generate --schema=pg-db/prisma/schema.prisma

EXPOSE 8080

CMD ["bun", "--cwd", "backend", "run", "start"]